version: "3"

services:

  sharetransport-db:
    image: neo4j:3.5.3
    container_name: sharetransport-db
    ports:  
    - 7474:7474
    - 7687:7687
    volumes:
    - ./data:/data
    - ./init:/init

