version: "3"

services:

  sharetransport-db:
    image: bruenni/sharetransport-neo4j
    build: ./docker
    container_name: sharetransport-neo4j
    ports:  
    - 7474:7474
    - 7687:7687
    volumes:
    #- ./data:/data
    - ./init:/init

