version: "3.6"

services:

  neo4j:
    image: bruenni/sharetransport-neo4j:3.5.14
    build: ./
    container_name: sharetransport-neo4j
    ports:
    - 7474:7474
    - 7687:7687
    environment:
      - NEO4J_AUTH=none
      # https://neo4j.com/docs/labs/apoc/3.5/introduction/
      - NEO4J_dbms_security_procedures_unrestricted=apoc.\\\*
    # volumes:
    #- ./data:/data
    # - ./neo4j/cypher:/init

